[package]
name = "kapplier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
axum = "0.7.5"
clap = { version = "4.5.4", features = ["derive", "env"] }
ctrlc = { version = "3.4.4", features = ["termination"] }
futures = "0.3.30"
k8s-openapi = { version = "0.21.1", features = ["latest"] }
kube = { version = "0.90.0", features = ["runtime", "derive"] }
lazy_static = "1.4.0"
log = "0.4.21"
openssl = { version = "0.10", features = ["vendored"] }
prometheus = { version = "0.13.3", features = ["process"] }
serde = "1.0.199"
serde_json = "1.0.116"
serde_yaml = "0.9.33"
simple_logger = "5.0.0"
tokio = { version = "1.37.0", features = ["full"] }
walkdir = "2.5.0"
